project:
  name: imdb_text_classification
paths:
  raw_data: data/aclImdb
  processed_dir: data/processed
  results_dir: results
  logs_dir: logs
preprocessing:
  lowercase: true
  expand_contractions: true
  remove_non_alpha: false
  demojize: false
tokenization:
  use_lemmatization: true
  max_length: 256
features:
  tfidf_max_features: 20000
  tfidf_ngram_range: [1,2]
training:
  model_name: distilbert-base-uncased
  batch_size: 8
  eval_batch_size: 16
  num_epochs: 1
  learning_rate: 5e-5
  device: cpu
