# config/config.yaml

data:
  base_path: "data/raw/aclImdb"   # where your IMDB dataset lives
  encoding: "utf-8"

preprocessing:
  lowercase: true
  remove_punctuation: true
  remove_stopwords: true
  lemmatize: false
  max_features: 5000

model:
  type: "logistic_regression"   # later you can switch to "svm" or "transformer"
  logistic_regression:
    max_iter: 1000
    random_state: 42

training:
  test_size: 0.2
  random_state: 42

results:
  model_dir: "results/models"
  metrics_file: "results/metrics.json"
